sudo: false

language: python

python:
  - "2.7"
  - "3.5"
  - "pypy"

install:
  - pip install -U pip
  - pip install -U setuptools
  - pip install .
  - pip install faker
  - pip install pytest-cov

script:
  - py.test --cov=./datatables

after_success:
  - bash <(curl -s https://codecov.io/bash)
